Running the TestExperiment from the command line (after copying ns3.cc output file to FNCS ns3 dir):
[sean@siftworkstation ns-3.19]$ cp /media/sf_FedoraVM/prosser-api/out/ns3.cc ~/FNCS-ns-allinone-3.19/ns-3.19/scratch/ns3.cc | ./waf --run scratch/ns3

Gives this warning:

Waf: Entering directory `/home/sean/FNCS-ns-allinone-3.19/ns-3.19/build'
[ 751/1563] cxx: scratch/ns3.cc -> build/scratch/ns3.cc.2.o
../scratch/ns3.cc:21:22: fatal error: ns3/fncs.h: No such file or directory
 #include "ns3/fncs.h"
                      ^
compilation terminated.
Waf: Leaving directory `/home/sean/FNCS-ns-allinone-3.19/ns-3.19/build'
Build failed
 -> task in 'ns3' failed (exit status 1): 
	{task 140296270168528: cxx ns3.cc -> ns3.cc.2.o}
['/usr/bin/g++', '-g', '-O2', '-pthread', '-I.', '-I..', '-DNS3_ASSERT_ENABLE', '-DNS3_LOG_ENABLE', '-DHAVE_SYS_IOCTL_H=1', '-DHAVE_IF_NETS_H=1', '-DHAVE_NET_ETHERNET_H=1', '-DHAVE_PACKET_H=1', '-DHAVE_IF_TUN_H=1', '-DHAVE_GSL=1', '../scratch/ns3.cc', '-c', '-o', 'scratch/ns3.cc.2.o']

The bad headers are added in Ns3Network.java lines 296 & 297